### ISSUE TITLE
Broken Abstract @Repository generation in KSP

### ISSUE THREAD

**Issue by mitasov-ra** [Tinkoff/kora#165]
I've tried to generate implementation for Abstract @Repository class, but generated implementation doesn't compile:

```java
public class `$AbstractFooRepository_Impl`(
  _jdbcConnectionFactory: JdbcConnectionFactory,
  _executor: Executor,
  _result_mapper_1: JdbcResultSetMapper<Foo>
) : AbstractFooRepository(/* MISSING CONSTRUCTOR PARAMETER */), JdbcRepository {
  // ...
}
```

P.S. It turned out that the reason was that the constructor of my abstract class was protected. I removed the protected modifier and now everything works:

```java
// THIS DOESN'T WORK
abstract class AbstractFooRepository protected constructor(/* params */)

// THIS DOES
abstract class AbstractFooRepository(/* params */)
```

**Comment by GoodforGod** [comment]
Examples works fine in `0.12.0`, tests reinforced to reduce chance of breaking such behavior in future
