### ISSUE TITLE
Escape `?` tokens in SQL in generated JdbcReposiory impl

### ISSUE THREAD

**Issue by mitasov-ra** [Tinkoff/kora#175]
In PostgreSQL we have JSON/JSONB operators: `?`, `?|`, `?&` etc. (https://www.postgresql.org/docs/12/functions-json.html)

PostgreSQL JDBC driver has an escape sequence for `?` - `??`.

Is it possible to automatically escape `?` in `@Query` annotations, as query syntax in them allows only named params, so it isn't clear that `?` still needs to be escaped.

### Example

```sql
SELECT *
FROM foo
WHERE foo.name = :name AND foo.json_data ? :keyName
```

Produces

```
ru.tinkoff.kora.database.jdbc.RuntimeSqlException: No value specified for parameter 3.
```

**Comment by GoodforGod** [comment]
This will require Query analysis, so this is not what Kora repository design intends to do

You should manually escape `?` in such cases
