### ISSUE TITLE
Exception when interface with @Repository extends any other interface

### ISSUE THREAD

**Issue by aleksander-molev** [Tinkoff/kora#52]
For example: we have some repository interface like

```java
@Repository
interface DocumentRepository extends JdbcQueryExecutorAccessor, BatchOperation{
    @Query("insert into ....")
    void someInsert();
   @Query("insert into .... from :fields ...")
    void someBatchInsert(@Batch List<String> fields);
}
```

where BatchOperation just common interface for set of different repositories, it looks like:

```java
interface BatchOperation {
   void someBatchInsert(List<String> fields);
}
```

it contains neither `@Repositor` nor `@Query` annotations, as we don't want to generate such repository.
We are getting compilation exception which tells us, that BatchOperations abstract methods don't have annotations `@Query`.
Exception:  error: Non-static abstract method has no `@Query` annotation

**Comment by Squiry** [comment]
Was fixed in `0.10.0` tag.
